# Generated by Django 3.1.4 on 2021-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='1', upload_to='images'),
            preserve_default=False,
        ),
    ]
