# Generated by Django 3.1.4 on 2021-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210923_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
